feat(voting-verifier): allow end poll to complete before expiration if a result has reached quorum
axelarnetwork/axelar-amplifier pull request #173
Opened 2023-10-27 23:15 UTC by eguajardo

## Description
Prerequisite to integrate voting with rewards. Before this change a poll is completed only when the poll is expired or when everyone voted. In order to integrate with rewards, it should be allowed to be completed when the quorum is satisfied to allow for a grace period between expiration and poll completion

https://axelarnetwork.atlassian.net/browse/AXE-2201

## Todos

- [x] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [x] Connect epics/issues

## Steps to Test

## Expected Behaviour

## Other Notes

2023-10-30 16:40 UTC, cjcobb23 approved these changes

2023-10-30 16:42 UTC, cjcobb23 commented on packages/axelar-wasm-std/src/voting.rs
> +            .votes
I feel like this field should be called `tallies`

2023-10-30 17:30 UTC, haiyizxx requested changes

2023-10-30 17:30 UTC, haiyizxx commented on packages/axelar-wasm-std/src/voting.rs
> +            results,
in line 229 `self.status = PollStatus::Finished;` means no more votes on the partial tally

2023-10-30 20:35 UTC, fish-sammy approved these changes

2023-10-30 20:35 UTC, fish-sammy commented on packages/axelar-wasm-std/src/voting.rs
> +            .collect();
```suggestion
        let quorum: Uint256 = self.quorum.into();
        let results: Vec<bool> = self.votes.iter().map(|tally| *tally >= quorum).collect();
```

2023-10-31 06:11 UTC, haiyizxx approved these changes

2023-10-31 15:19 UTC, merged