refactor(multisig): convert KeyGen into RegisterWorkerSet
axelarnetwork/axelar-amplifier pull request #194
Opened 2023-11-16 20:01 UTC by fahimahmedx

## Description
[AXE-2514]

The goal of this PR is to rename `KeyGen` as `RegisterWorkerSet` and replace its three parameters with a `WorkerSet`.

## Todos
- [ ] Determine how to refactor `key_gen()` and `do_key_gen()` test functions to use `WorkerSet` instead of `Key`
- [ ] Fix `signer_pub_key()` by returning a copy of the `PublicKey`
- [ ] Determine how to fix the test cases in `multisig::signing` by replacing `Key` in the config with a `WorkerSet`
- [ ] Unit tests
- [ ] `cargo fmt`
- [ ] Documentation

## Steps to Test
`cargo test`

2023-11-17 15:16 UTC, cjcobb23 requested changes

2023-11-17 15:16 UTC, cjcobb23 commented on contracts/multisig/src/signing.rs
> +    pub key_id: WorkerSetID,
rename to worker_set_id

2023-11-17 15:16 UTC, cjcobb23 commented on contracts/multisig/src/contract.rs
> +        let worker_set_id = WorkerSetID {
Just use `worker_set.id()` as the id

2023-11-17 15:16 UTC, cjcobb23 commented on contracts/multisig/src/contract.rs
>          key_id: String,
This should be the worker set id now

2023-11-17 15:16 UTC, cjcobb23 commented on contracts/multisig/src/events.rs
> +        key_id: WorkerSetID,
rename to worker_set_id

2023-11-17 15:16 UTC, cjcobb23 commented on contracts/multisig/src/msg.rs
> +    GetKey { key_id: WorkerSetID },
```suggestion
    GetKey { worker_set_id: WorkerSetID },
```

2023-11-17 15:16 UTC, cjcobb23 commented on contracts/multisig/src/types.rs
> +pub struct WorkerSetID {
We shouldn't need this struct. WorkerSet already has an `id()` method that returns an id

2023-11-21 19:02 UTC, cjcobb23 commented on contracts/multisig/src/worker_set.rs
> +        pub_keys
```suggestion
        self.signers.iter().map(|(address, signer)| {
            (address.clone(), signer.pub_key.clone())
        }).collect()
```

2023-11-21 20:51 UTC, fahimahmedx commented on contracts/multisig/src/worker_set.rs
> +    }
I was thinking that it would increase readability.
What do you think @cgorenflo?

2023-11-21 21:56 UTC, cgorenflo commented on contracts/multisig/src/state.rs
> +pub const WORKER_SETS: Map<&String, WorkerSet> = Map::new("worker_sets");
even better, create an alias for `String`, e.g.
```
type WorkerSetId = String
```

2023-11-21 21:56 UTC, cgorenflo commented on contracts/multisig/src/worker_set.rs
> +    }
In this case I agree with @cjcobb23. The worker set doesn't really know anything about sessions or participations. Consequently, if you remove the creation of this error message, the function doesn't really do anything anymore

2023-11-21 23:19 UTC, fahimahmedx commented on contracts/multisig/src/state.rs
> +pub const WORKER_SETS: Map<&String, WorkerSet> = Map::new("worker_sets");
that is really convenient, learning something new everyday! just added, thanks for the suggestion @cgorenflo!

2023-11-22 00:31 UTC, cgorenflo commented on contracts/multisig/src/state.rs
>      worker_set_id: &String,
```suggestion
    worker_set_id: &str,
```

2023-11-22 17:00 UTC, cgorenflo approved these changes

2023-11-28 15:02 UTC, cjcobb23 approved these changes

2023-11-28 17:15 UTC, merged