refactor: remove reference values in uint.rs
axelarnetwork/axelar-amplifier pull request #195
Opened 2023-11-16 20:49 UTC by fahimahmedx

## Description
[AXE-2636]
Integers are small enough in size that they can be copied instead of referenced. This PR removes unnecessary usages of a reference `nonempty::Uint`.

## Steps to Test
`cargo test` passes

2023-11-16 21:01 UTC, cgorenflo approved these changes

2023-11-16 21:01 UTC, cjcobb23 commented
uint256 is not that small fwiw

2023-11-16 21:02 UTC, cjcobb23 requested changes
why are we copying uint256 now?

2023-11-17 01:35 UTC, cjcobb23 commented on packages/axelar-wasm-std/src/nonempty/uint.rs
> -
Can we implement `AsRef`?

2023-11-17 01:35 UTC, cjcobb23 commented on packages/axelar-wasm-std/src/snapshot.rs
> +                let weight: Uint256 = participant.weight.into();
And then can we just use `AsRef` here?

2023-11-17 01:35 UTC, cjcobb23 commented on packages/axelar-wasm-std/src/snapshot.rs
> +            .map(|p| p.weight.into())
And use `AsRef` here too?

2023-11-22 21:24 UTC, cjcobb23 approved these changes

2023-11-23 16:57 UTC, merged