feat(minor-multisig-prover): encode ApproveMessages function calldata
axelarnetwork/axelar-amplifier pull request #387
Opened 2024-05-08 15:46 UTC by haiyizxx

## Description

## Todos

- [ ] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues

## Steps to Test

## Expected Behaviour

## Other Notes

2024-05-08 19:42 UTC, cgorenflo approved these changes

2024-05-09 14:01 UTC, fish-sammy requested changes

2024-05-09 14:29 UTC, haiyizxx commented on contracts/multisig-prover/src/encoding/abi2/execute_data.rs
> +impl From<Message> for IAxelarAmplifierGateway::Message {
I noticed, want to refactor in a separate pr

2024-05-09 15:29 UTC, haiyizxx commented on contracts/multisig-prover/src/encoding/abi2/execute_data.rs
> +impl From<Message> for IAxelarAmplifierGateway::Message {
Created a [ticket](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/18?selectedIssue=AXE-3963) to track this

2024-05-09 16:18 UTC, fish-sammy approved these changes

2024-05-09 16:22 UTC, merged