chore: refactor ChainName for better serialization
axelarnetwork/axelar-amplifier pull request #49
Opened 2023-07-28 17:41 UTC by haiyizxx

2023-08-17 20:06 UTC, sammy1991106 approved these changes

2023-08-18 05:00 UTC, sammy1991106 requested changes

2023-08-18 05:00 UTC, sammy1991106 commented on contracts/connection-router/src/types.rs
> +            .map_err(|_| ContractError::InvalidChainName {})
```suggestion
```

2023-08-18 05:32 UTC, cgorenflo approved these changes

2023-08-18 12:39 UTC, merged