feat: add service-registry-api package
axelarnetwork/axelar-amplifier pull request #610
Opened 2024-09-09 14:07 UTC by maancham

## Description

AXE-4789

## Todos

- [ ] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues

## Steps to Test

## Expected Behaviour

## Other Notes

2024-09-09 14:54 UTC, cjcobb23 commented
why do we need this?

2024-09-10 15:59 UTC, cgorenflo commented
> why do we need this?

to break the cyclic dependency between service-registry and coordinator

2024-09-10 19:47 UTC, cjcobb23 commented
> > why do we need this?
> 
> to break the cyclic dependency between service-registry and coordinator

For what exactly? Is there a planned change that will create a cyclic dependency?

2024-09-13 22:16 UTC, cgorenflo requested changes

2024-09-13 22:16 UTC, cgorenflo commented on packages/service-registry-api/src/primitives.rs
> +}
we'll have to look into how the verifier is used in other contracts. It doesn't make sense to provide this logic outside of the service-registry

2024-09-13 22:16 UTC, cgorenflo commented on packages/service-registry-api/src/primitives.rs
> +pub const VERIFIER_WEIGHT: nonempty::Uint128 = nonempty::Uint128::one();
state definitely shouldn't go into this crate

2024-09-13 22:16 UTC, cgorenflo commented on packages/service-registry-api/src/primitives.rs
> +pub const VERIFIERS: Map<(&ServiceName, &VerifierAddress), Verifier> = Map::new("verifiers");
no state

2024-09-18 15:40 UTC, cgorenflo approved these changes

2024-09-18 16:13 UTC, merged