feat(ampd): add Stacks handlers
axelarnetwork/axelar-amplifier pull request #728
Opened 2024-12-16 14:25 UTC by raress96

## Description

Stacks verify msg & verify verifier set handlers.

2025-01-02 19:42 UTC, cjcobb23 requested changes

2025-01-02 19:42 UTC, cjcobb23 commented on ampd/src/stacks/contract_verifier.rs
> +
I am worried about the performance implications of this. As far as I can tell, this is downloading two sets of source code and then comparing them? Is it comparing a hash of the source code or the full bytes of the source code?

2025-01-02 19:42 UTC, cjcobb23 commented on ampd/src/stacks/verifier.rs
> +            let result = get_verify_contract_params(event);
I still don't think this functionality should exist in ampd. Suddenly now ampd is doing something different than what it normally does (verify gmp messages and verify verifier set rotations). This change opens the door for ampd to start doing all kinds of custom logic, and just makes the code and system more complicated to reason about and maintain. Even from a performance perspective, we need to be aware of the overhead of attempting to verify contract deployments now. I don't think we should go down this route.

2025-01-13 11:03 UTC, raress96 commented on ampd/src/stacks/verifier.rs
> +            let result = get_verify_contract_params(event);
The contract verification logic was removed, no custom logic for Stacks is now in ampd.

2025-01-13 11:04 UTC, raress96 commented on ampd/src/stacks/contract_verifier.rs
> +
No longer applicable

2025-03-13 16:12 UTC, eguajardo requested changes

2025-03-13 16:12 UTC, eguajardo commented on ampd/src/stacks/finalizer.rs
> +        .as_u64())
I don't think this is enough to identify a finalized block in Stacks. If I'm understanding the [documentation](https://docs.stacks.co/concepts/block-production/bitcoin-reorgs#replaying-transactions-3) correctly, at the moment Stacks finality is tied to Bitcoin's finality. Wouldn't you need to take the anchored blocks in consideration instead of the normal blocks?

2025-03-14 07:07 UTC, raress96 commented on ampd/src/stacks/finalizer.rs
> +        .as_u64())
This was a discussion we had with the auditors & the Stacks Axelar contract developers. From my understanding, after the Stacks Nakamoto upgrade finality in Stacks should be instant, after a transaction is confirmed in a Stacks block, it should be final even if Bitcoin forks. Exceptions to this are Bitcoin-reliant transactions, which fetch state from Bitcoin, but the Stacks Axelar contract don't use such functionality:
https://docs.stacks.co/concepts/block-production/bitcoin-finality#nakamoto-transactions-and-bitcoin-reorgs

Initially we didn't even have this finalizer implemented, but we decided it would be best to add it if we want to configure a greater `confirmation_height` for Stacks other than 1 in the future. I will send this comment to the Stacks team which developed the contracts, to check if there is anything else I missed.

2025-03-14 11:16 UTC, raress96 commented on ampd/src/handlers/stacks_verify_msg.rs
> +    pub source_address: String,
`StacksAddress` only includes user account addresses, not smart contracts. I tried using `PrincipalData` but unfortunately it uses the default serde derive(Deserialize) which does not handle deserialization like it should...
The address is checked here however that it is a valid Stacks address:
https://github.com/axelarnetwork/axelar-amplifier/pull/728/files#diff-09b6aab36d03d4a95649534a32886c7b058e5fa87a85415221a80934c217c03cR77

Will try to see if I can get this working with some other type, but it doesn't seem possible and we will probably have to leave this as String here.

2025-03-24 10:07 UTC, raress96 commented on ampd/src/handlers/stacks_verify_msg.rs
> +            .get_finalized_transactions(tx_hashes, latest_finalized_block_height)
Done

2025-03-24 10:07 UTC, raress96 commented on ampd/src/stacks/http_client.rs
Done

2025-03-24 10:07 UTC, raress96 commented on ampd/src/lib.rs
> +                        Client::new_http(http_url.to_string().trim_end_matches('/').into()),
Done

2025-03-24 10:07 UTC, raress96 commented on ampd/src/lib.rs
> +                        Client::new_http(http_url.to_string().trim_end_matches('/').into()),
Done

2025-07-15 21:23 UTC, cjcobb23 approved these changes

2025-07-25 14:53 UTC, eguajardo approved these changes

2025-07-30 15:28 UTC, merged